//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> PossibleDiscount { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Cout { get; set; }
        public string Description { get; set; }
        public byte[] Photo { get; set; }
        public string Article { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
